project:
  type: website

website:
  title: "Two Parameters"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: analysis.qmd
        text: Analysis
      

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



